# Generated by Django 3.2.16 on 2022-10-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_urun_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='altkategori',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
