# Generated by Django 3.2.16 on 2022-10-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20221023_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='resim',
            field=models.FileField(default=1, upload_to='kategori/'),
            preserve_default=False,
        ),
    ]
