# Generated by Django 3.2.16 on 2022-10-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20221023_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stok',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
