# Generated by Django 3.2.16 on 2022-10-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_urun_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='altkategori',
            name='stok',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='stok',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
