# Generated by Django 3.2.16 on 2022-10-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20221028_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='stok',
            field=models.IntegerField(),
        ),
    ]
