# Generated by Django 3.2.16 on 2022-10-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_sepet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sepet',
            old_name='sepetAdet',
            new_name='adet',
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='sepetToplam',
            new_name='fiyat',
        ),
    ]
