# Generated by Django 3.2.16 on 2022-10-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20221029_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sepet',
            old_name='adet',
            new_name='sepetAdet',
        ),
        migrations.RenameField(
            model_name='sepet',
            old_name='fiyat',
            new_name='sepetFiyat',
        ),
    ]
