# Generated by Django 3.2.16 on 2022-10-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20221030_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='stok',
        ),
    ]
