# Generated by Django 3.2.16 on 2022-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_remove_urun_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stok',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
