# Generated by Django 3.2.16 on 2022-11-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_favori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favori',
        ),
    ]
