# Generated by Django 3.2.16 on 2022-11-06 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0019_delete_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='favori',
            field=models.ManyToManyField(related_name='favori_urun', to=settings.AUTH_USER_MODEL),
        ),
    ]
