# Generated by Django 3.2.16 on 2022-11-06 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0020_urun_favori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='favori',
            field=models.ManyToManyField(blank=True, related_name='favori_urun', to=settings.AUTH_USER_MODEL),
        ),
    ]
