# Generated by Django 3.2.16 on 2022-11-07 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0022_auto_20221106_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='favori',
            field=models.ManyToManyField(blank=True, related_name='favori', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favori',
        ),
    ]
