# Generated by Django 3.2.16 on 2022-11-27 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0024_auto_20221107_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField(max_length=400, verbose_name='yorum')),
                ('yorumTarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to='myApp.urun')),
            ],
        ),
    ]
